### ISSUE TITLE
"java.lang.IllegalStateException: Location is not set" at start.

### ISSUE THREAD

**Issue by billbarni** [benneq/spring-boot-javafx-sample#1]
Everytime the appilcation starts, I get this error:

```
Caused by: java.lang.IllegalStateException: Location is not set.
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
    at de.benneq.springbootjavafxsample.common.SpringFXMLLoader.load(SpringFXMLLoader.java:46)
    at de.benneq.springbootjavafxsample.common.SpringFXMLLoader.load(SpringFXMLLoader.java:29)
    at de.benneq.springbootjavafxsample.common.FXMLController.afterPropertiesSet(FXMLController.java:23)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
    ... 46 more
```

**Comment by ntholi** [comment]
did you ever get the solution? I'm having the same error on my JavaFX project after adding spring boot

**Comment by benneq** [comment]
Do you get the error with MY sample app or with YOUR project?

I just redownloaded my project and it still works without any error :)
